spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pn1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true

logging:
  level:
    root: info
    com.pn.blog: debug
  file:
    name: /log/blog-dev.log

server:
  port: 8181
